// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ShowGanttController from "./show_gantt_controller"
application.register("show-gantt", ShowGanttController)

import TodoController from "./todo_controller";
application.register("todo", TodoController);
